### ISSUE TITLE
Does Kernal ROMs on the Versa64Cart work?

### ISSUE THREAD

**Issue by C-64Bram** [bwack/Versa64Cart#3]
Hi Bwack.
I just saw your Versacart and it looks like a great piece of work! I understand it can hold up to 8 programs , each 8kb in a 512 eprom and each of the 8kb can be selected by changing the dipswitches. Perhaps a stupid question but I was wondering: can the Versacart be used to switch between kernelroms as well? So 8 different kernals in a 512 KB eprom and switch between Them by changing the dipswitches?
Best regards,
Bram.

**Comment by VintageProject** [comment]
Hi Bram,
the switching mechanism is similar, I think. Both rely on working with address lines A13-A15 to select the appropriate 8kB bank. (8 kilobyte (kB) rather than 8 kilobit (kb))
Look at the switchless Kernal switcher here: https://github.com/bwack/C64-Switchless-Multi-Kernal-27C256-adapter
It's designed for 4 different Kernals with 8 kB each, so it only uses 256 kB instead of 512 kB. But the way it works would be very similar. Just add A13 to the equation.

It doesn't use DIP switches but rather a microcontroller that does the ROM selection and automatic reset for you. Thanks to bwack, I have one in my C64 and it works a treat!

Best regards,
Thilo

**Comment by C-64Bram** [comment]
HHi Thilo,
Thanks! I will try it when I am back from vacation. :-)
I will check out the kernal switcher for sure too!

Best regards,
Bram.


Op ma 16 jul. 2018 08:32 schreef Thilo N <notifications@github.com>:

**Comment by bwack** [comment]
Thanks. Late answer, but here is one in case more is wondering..
In ultimax mode (see docs), the cartridge replaces the kernal memory region with the cartridge rom, but I don't know what happens to the rest of the memory map, and if it is the same as just replacing the kernal ic. It must be tried. :)

**Comment by C-64Bram** [comment]
Hi.! I will try in a few days .
To busy with work at the time. :-(
Thank you for the answer!!

Best regards,
Bram.



Op za 22 sep. 2018 11:08 schreef bwack <notifications@github.com>:

**Comment by bwack** [comment]
I asked on facebook and got a reply that it won't work because even if you replace the kernal by putting the cart in ultimax mode, the c64 can only access 4k of the RAM. The kernal will not work then.

**Comment by C-64Bram** [comment]
Aha.
Thanks! No problem.
It is still a great design, this cartridge of yours. :-)
I am enjoying it very much!

Best regards, Bram

Op za 22 sep. 2018 21:41 schreef bwack <notifications@github.com>:

**Comment by bwack** [comment]
Thank you very much. Glad you like it :)
